
from __future__ import annotations

from typing import Dict, List, Tuple

CITY_ALIASES: Dict[str, List[str]] = {
    # --- Jawa ---
    "Jakarta": ["jakarta", "jkt", "dki jakarta", "jakarta pusat", "jakarta utara", "jakarta selatan", "jakarta barat", "jakarta timur", "jakpus", "jaksel", "jaktim", "jakbar", "jakut"],
    "Surabaya": ["surabaya", "sby", "suroboyo", "suruboyo city", "kota surabaya"],
    "Semarang": ["semarang", "smg"],
    "Bandung": ["bandung", "bdg", "kota bandung", "bandung kota"],
    "Yogyakarta": ["yogyakarta", "jogja", "yogya", "diy", "ykg", "kota yogyakarta"],
    "Solo": ["solo", "surakarta", "slo", "kota solo"],
    "Malang": ["malang", "mlg"],
    "Cirebon": ["cirebon", "crb"],
    "Bekasi": ["bekasi","bks"],
    "Tangerang" : ["tangerang", "tng", "tangerang selatan", "tangsel", "bsd", "bsd city"],
    "Bogor": ["bogor", "bgr"],
    "Depok": ["depok", "dpk"],
    "Cilegon": ["cilegon", "clg"],
    "Gresik": ["gresik", "gsx"],
    "sidoarjo" : ["sidoarjo", "sda"],
    "Purwakarta": ["purwakarta", "pwk"],
    "Karawang": ["karawang", "krw"],
    "Sukabumi": ["sukabumi", "smi"],
    "Tasikmalaya": ["tasikmalaya", "tsm"],
    "Kediri": ["kediri", "kdr"],
    "Jember": ["jember", "jmr"],
    "Banyuwangi": ["banyuwangi", "bwx"],
    "Magelang": ["magelang", "mgl"],
    "Pekalongan": ["pekalongan", "pkl"],
    "Tegal": ["tegal", "tgl"],
    "Purwokerto": ["purwokerto", "pwt"],
    "Kudus": ["kudus"],
    "Madiun": ["madiun"],
    "Probolinggo": ["probolinggo"],
    # --- Sumatera ---
    "Medan": ["medan", "mdn"],
    "Palembang": ["palembang", "plg"],
    "Batam": ["batam", "btm"],
    "Pekanbaru": ["pekanbaru", "pku", "riau"],
    "Padang": ["padang", "pdg"],
    "Lampung": ["lampung", "bandar lampung", "bdl", "tjk"],
    "Banda Aceh": ["banda aceh", "aceh", "btj"],
    "Jambi": ["jambi", "djb"],
    "Bengkulu": ["bengkulu", "bgl"],
    "Pangkalpinang": ["pangkalpinang", "pangkal pinang", "pgk", "bangka"],
    "Tanjung Pinang": ["tanjung pinang", "tanjungpinang", "tnj"],
    "Dumai": ["dumai", "dum"],
    "Lubuklinggau": ["lubuklinggau", "llg"],
    # --- Kalimantan ---
    "Balikpapan": ["balikpapan", "bpp"],
    "Banjarmasin": ["banjarmasin", "bjm"],
    "Pontianak": ["pontianak", "ptk"],
    "Samarinda": ["samarinda", "smd"],
    "Palangkaraya": ["palangkaraya", "palangka raya", "pky"],
    "Tarakan": ["tarakan", "trk"],
    "Singkawang": ["singkawang"],
    "Bontang": ["bontang"],
    "Banjarbaru": ["banjarbaru"],
    # --- Sulawesi ---
    "Makassar": ["makassar", "ujung pandang", "mks"],
    "Manado": ["manado", "mdc"],
    "Palu": ["palu", "plw"],
    "Kendari": ["kendari", "kdi"],
    "Gorontalo": ["gorontalo", "gto"],
    "Mamuju": ["mamuju", "mju"],
    "Bitung": ["bitung"],
    "Parepare": ["parepare", "pare-pare"],
    "Palopo": ["palopo"],
    "Baubau": ["baubau", "bau-bau"],
    # --- Bali & Nusa Tenggara ---
    "Denpasar": ["denpasar", "bali", "dps"],
    "Mataram": ["mataram", "lombok", "ami"],
    "Kupang": ["kupang", "koepang", "koe"],
    "Labuan Bajo": ["labuan bajo", "lbj"],
    "Bima": ["bima"],
    "Ende": ["ende"],
    "Sumbawa": ["sumbawa"],
    # --- Papua & Maluku ---
    "Ambon": ["ambon", "amq"],
    "Jayapura": ["jayapura", "papua", "djj"],
    "Ternate": ["ternate", "tte"],
    "Sorong": ["sorong", "soq"],
    "Manokwari": ["manokwari", "mkw"],
    "Merauke": ["merauke", "mko"],
    "Timika": ["timika", "tim"],
    "Biak": ["biak", "bik"],
}

DANGEROUS_GOODS_TRAINING_DATA: list[tuple[str, int]] = [
    # --- Explosives ---
    ("bahan peledak", 1),
    ("dinamit", 1),
    ("kembang api", 1),
    ("petasan besar", 1),
    ("amunisi peluru", 1),
    ("mesiu", 1),
    ("tnt", 1),
    ("detonator", 1),
    ("bom asap", 1),
    ("mercon banting", 1),
    ("flare darurat kapal", 1),
    ("suar sinyal", 1),
    ("bubuk mesiu hitam", 1),
    ("peluru senapan angin", 1),
    ("proyektil amunisi", 1),
    ("kembang api kawat", 1),
    ("petasan korek", 1),
    # --- Gases ---
    ("tabung gas lpg", 1),
    ("elpiji", 1),
    ("gas oksigen bertekanan", 1),
    ("gas alam cair lng", 1),
    ("gas beracun", 1),
    ("tabung gas elpiji 12kg", 1),
    ("gas nitrogen cair", 1),
    ("aerosol bertekanan tinggi", 1),
    ("kaleng freon ac", 1),
    ("gas asetilena las", 1),
    ("gas klorin", 1),
    ("gas helium bertekanan", 1),
    ("gas butane portabel", 1),
    ("gas korosif", 1),
    ("tabung oksigen medis cair", 1),
    ("isi ulang gas korek api", 1),
    ("pilox aerosol", 1),
    ("cat semprot aerosol", 1),
    ("spray pengharum ruangan aerosol bertekanan", 1),
    # --- Flammable liquids/solids ---
    ("bensin", 1),
    ("solar", 1),
    ("minyak tanah", 1),
    ("alkohol murni", 1),
    ("spiritus", 1),
    ("thinner", 1),
    ("cat minyak mudah terbakar", 1),
    ("pelarut kimia mudah terbakar", 1),
    ("avtur", 1),
    ("korek api batangan", 1),
    ("fosfor putih", 1),
    ("magnesium serbuk", 1),
    ("bahan bakar cair", 1),
    ("minyak bakar industri", 1),
    ("pertamax", 1),
    ("pertalite", 1),
    ("aseton pembersih cat kuku", 1),
    ("alkohol 96 persen", 1),
    ("ethanol industri", 1),
    ("parafin cair mudah terbakar", 1),
    ("minyak zippo", 1),
    ("vernies kayu berbasis tiner", 1),
    ("kalsium karbida batu karbit", 1),
    ("resin kimia cair flammable", 1),
    ("lem aica aibon cair", 1),
    ("arang aktif panas mandiri", 1),
    ("kapur tohor spontan panas", 1),
    # --- Oxidizers ---
    ("kalium permanganat", 1),
    ("hidrogen peroksida pekat", 1),
    ("pupuk amonium nitrat", 1),
    ("kalsium hipoklorit", 1),
    ("natrium nitrat", 1),
    ("kaporit bubuk pekat", 1),
    ("pupuk kimia oksidator tinggi", 1),
    ("peroksida organik", 1),
    ("bleaching powder pekat industri", 1),
    # --- Toxic / infectious ---
    ("pestisida", 1),
    ("insektisida racun", 1),
    ("limbah medis infeksius", 1),
    ("bahan kimia beracun", 1),
    ("sianida", 1),
    ("racun tikus", 1),
    ("herbisida cair", 1),
    ("limbah b3", 1),
    ("racun serangga cair pekat", 1),
    ("sampel darah infeksius", 1),
    ("virus sampel laboratorium", 1),
    ("bakteri patogen cair", 1),
    ("racun Arsenik", 1),
    ("fungisida tanaman beracun", 1),
    ("nikotin murni cair pekat", 1),
    # --- Radioactive ---
    ("bahan radioaktif", 1),
    ("uranium", 1),
    ("limbah nuklir", 1),
    ("sumber radiasi medis", 1),
    ("plutonium", 1),
    ("isotor radioaktif cair", 1),
    ("kobalt 60 industri", 1),
    # --- Corrosives ---
    ("asam sulfat", 1),
    ("asam klorida", 1),
    ("soda api", 1),
    ("baterai asam basah", 1),
    ("air keras", 1),
    ("cairan pembersih korosif industri", 1),
    ("natrium hidroksida cair", 1),
    ("asam nitrat", 1),
    ("cairan air aki zuur", 1),
    ("pembersih porselen korosif tinggi", 1),
    ("cairan etsa logam korosif", 1),
    # --- Misc dangerous ---
    ("baterai lithium jumlah besar", 1),
    ("aki bekas mengandung asam", 1),
    ("merkuri", 1),
    ("asbes", 1),
    ("gas air mata", 1),
    ("senjata api", 1),
    ("bubuk kimia berbahaya tidak berlabel", 1),
    ("powerbank kapasitas raksasa diatas 100wh", 1),
    ("es kering dry ice", 1),
    ("baterai sepeda listrik lithium massal", 1),
    ("air raksa murni", 1),
    ("magnet industri daya tarik sangat kuat", 1),
    ("limbah elektronik B3", 1),
    ("stunt gun alat kejut listrik", 1),
    ("senapan angin peluru pelet", 1),
    ("pisau komando sangkur", 1),
    # --- Safe: textiles / apparel ---
    ("tekstil", 0),
    ("kain katun", 0),
    ("pakaian jadi", 0),
    ("baju kaos", 0),
    ("sepatu olahraga", 0),
    ("tas kulit sintetis", 0),
    ("kain batik", 0),
    ("celana jeans", 0),
    ("jaket musim dingin", 0),
    ("kerudung jilbab", 0),
    ("sepatu pantofel", 0),
    ("sandal karet", 0),
    ("handuk mandi", 0),
    ("kaos kaki katun", 0),
    ("topi baseball", 0),
    ("kain sutra sintetis", 0),
    ("pakaian dalam wanita", 0),
    ("jas hujan plastik", 0),
    # --- Safe: electronics (consumer, not bulk battery) ---
    ("handphone baru", 0),
    ("laptop", 0),
    ("komponen elektronik kecil", 0),
    ("televisi led", 0),
    ("kabel listrik", 0),
    ("charger hp", 0),
    ("speaker bluetooth", 0),
    ("mouse komputer", 0),
    ("keyboard mekanik", 0),
    ("headphone kabel", 0),
    ("earphone wired", 0),
    ("modem wifi portabel non baterai", 0),
    ("kamera mirrorless", 0),
    ("kabel hdmi", 0),
    ("smartwatch", 0),
    ("kipas angin meja", 0),
    ("rice cooker magic com", 0),
    ("setrika listrik", 0),
    # --- Safe: furniture / household ---
    ("furniture kayu", 0),
    ("mebel jati", 0),
    ("kursi plastik", 0),
    ("lemari pakaian", 0),
    ("peralatan rumah tangga", 0),
    ("karpet", 0),
    ("gorden", 0),
    ("sprei dan bantal", 0),
    ("perabot dapur stainless", 0),
    ("kasur busa", 0),
    ("meja belajar anak", 0),
    ("rak sepatu plastik", 0),
    ("jemuran aluminium", 0),
    ("sapu dan pengki", 0),
    ("piring keramik dapur", 0),
    ("wajan teflon penggorengan", 0),
    # --- Safe: goods / consumables ---
    ("mainan anak", 0),
    ("buku pelajaran", 0),
    ("alat tulis kantor", 0),
    ("kertas hvs", 0),
    ("makanan kering kemasan", 0),
    ("snack ringan", 0),
    ("kopi bubuk", 0),
    ("teh celup", 0),
    ("beras", 0),
    ("gula pasir", 0),
    ("keramik lantai", 0),
    ("gelas kaca pecah belah", 0),
    ("sparepart motor non aki", 0),
    ("kosmetik non aerosol", 0),
    ("sayur segar", 0),
    ("buah-buahan", 0),
    ("ikan beku kemasan", 0),
    ("daging beku kemasan", 0),
    ("obat resep non narkotik", 0),
    ("produk kertas tisu", 0),
    ("boneka mainan", 0),
    ("alat olahraga raket", 0),
    ("sepeda lipat", 0),
    ("aksesoris fashion", 0),
    ("perhiasan imitasi", 0),
    ("produk kulit dompet", 0),
    ("botol plastik kosong", 0),
    ("kardus kosong", 0),
    ("plastik kemasan jadi", 0),
    ("payung lipat", 0),
    ("koper travel", 0),
    ("peralatan kantor printer", 0),
    ("biskuit kaleng", 0),
    ("susu bubuk kemasan", 0),
    ("mie instan kardus", 0),
    ("minyak goreng kelapa sawit pouch", 0),
    ("bumbu dapur kering", 0),
    ("vitamin tablet botol", 0),
    ("masker medis kain", 0),
    ("sabun mandi batang", 0),
    ("shampo botol plastik", 0),
    ("pasta gigi tube", 0),
    ("lotion pelembab kulit", 0),
    ("parfum botol kaca non aerosol", 0),
    ("pakan kucing kering", 0),
    ("pakan burung biji-bijian", 0),
    ("pot bunga plastik", 0),
    ("baut dan mur besi", 0),
    ("oli mesin disegel pabrik", 0),
    ("ban luar mobil", 0),
    ("helm motor SNI", 0),
    ("velg mobil aluminium", 0),
]

import json
from pathlib import Path

DATASET_PATH = Path(__file__).parent / "manifest_dataset.json"

def load_manifest_benchmark_data() -> list[dict]:
    """Membaca 5000 data manifes dari file JSON secara instan."""
    if DATASET_PATH.exists():
        with open(DATASET_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    return []

MANIFEST_BENCHMARK_DATA = load_manifest_benchmark_data()

DANGEROUS_GOODS_TRAINING_DATA = [
    (item["raw_text"], 1 if item["ground_truth"]["is_dangerous"] else 0)
    for item in MANIFEST_BENCHMARK_DATA
]